### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by testillano** [manusa/actions-setup-minikube#37]
here:
https://github.com/manusa/actions-setup-minikube/blob/965c2006a2cf6c24971b6419ccacf46a2c1b0065/action.yml#L17

(description)

**Comment by manusa** [comment]
Hi @testillano ,
Thank you for reporting, would you like to contribute a PR to fix it?

**Comment by testillano** [comment]
ok i could try

**Comment by testillano** [comment]
i have the fix in a local branch, but don't know the procedure to PR (never did).

**Comment by manusa** [comment]
Hi @testillano 
I'm assuming you cloned this repo and not your own fork.
First step in order to create a GitHub pull request (in a repo you don't own or are authorized) is creating your own fork.
So go ahead and press this button:
![image](https://user-images.githubusercontent.com/488391/113844416-bd312280-9794-11eb-872f-3bf60ebc38e2.png)

Once you are in your own fork, you can change the origin URL for your locally cloned repo:
```shell
git remote set-url origin git@github.com:testillano/actions-setup-minikube.git
## Or if using https
git remote set-url origin https://github.com/testillano/actions-setup-minikube.git
```

So you claimed you had the changes in your own branch (so probably already committed, we can skip that then)

Now you must push your branch to GitHub

```shell
git push origin $yourBranch
```

Next steps are really straight-forward.

You go to this repo's main site https://github.com/manusa/actions-setup-minikube and on the top part you should already see a button with a `compare & pull request` action. Press it and create your PR.

**Comment by testillano** [comment]
thank u for the explanation. I think I'd already done.

**Comment by manusa** [comment]
Merged :heart: thx for contributing
