### ISSUE TITLE
Need support Ubuntu 22

### ISSUE THREAD

**Issue by deadwind4** [manusa/actions-setup-minikube#61]
Ubuntu 22.04 has been released. Thanks.
https://ubuntu.com/blog/ubuntu-22-04-lts-released

**Comment by manusa** [comment]
Hi @deadwind4,

I'm not sure if your issue is specific to this repo (Action to setup Minikube on a GitHub CI environment), or the [official Minikube repository](https://github.com/kubernetes/minikube/).

AFAIK, there's no `22.04` Ubuntu action runner yet: https://github.com/actions/virtual-environments

**Comment by manusa** [comment]
Hi @deadwind4,


I just released [v2.7.0](https://github.com/manusa/actions-setup-minikube/releases/tag/v2.7.0) that supposedly works with Ubuntu 22.04, it would be great to have your feedback :pray:

**Comment by pan3793** [comment]
Thanks @manusa, we verified this patch through https://github.com/apache/incubator-kyuubi/pull/2585, everything goes well.

**Comment by manusa** [comment]
> Thanks @manusa, we verified this patch through [apache/incubator-kyuubi#2585](https://github.com/apache/incubator-kyuubi/pull/2585), everything goes well.

:tada: Awesome news, thx for sharing :heart:
