### ISSUE TITLE
Add the ability to select driver

### ISSUE THREAD

**Issue by MOZGIII** [manusa/actions-setup-minikube#9]
It would be great if we could choose a driver. minikube has a `docker` driver now, it should work at GHA, and I'd like to try it.

**Comment by manusa** [comment]
TIL, https://minikube.sigs.k8s.io/docs/drivers/docker/

When was this released?

Not sure of the advantages for this driver in GHA, since bare metal already uses Docker internally. End result will probably be the same, but will try.

**Comment by MOZGIII** [comment]
I guess in 1.19, I've seen it being used by default since that version at least. But idk for sure, you can check the release notes.

It'd also be nice to have an output that holds the effective drive that was used. I'd use it to run `eval $(minikube docker-env)` when the driver is `docker`, and skip it if it's `none`.

**Comment by manusa** [comment]
The thing is that with the current driver we are using, it shouldn't be necessary to run `eval $(minikube docker-env)` in your workflow.

We're using this in [Eclipse JKube](https://github.com/eclipse/jkube) E2E tests which for K8s creates local Docker images that can be then deployed into Minikube without the need to push them to a shared registry (since the Docker daemon is shared).

https://github.com/eclipse/jkube/blob/20768878a3de21eb5608347c0600f00d71b3d79b/.github/workflows/e2e-tests.yml#L59

Anyway, as I say, I'll give it a try.

**Comment by MOZGIII** [comment]
We've switched to using `minikube cache`, so getting the current driver it's no longer an issue.
It would be great to set it still though. For now, we switched to using a plain `run` command, hope to switch back to this action when the features we need are added.

**Comment by manusa** [comment]
Hi @MOZGIII,
Just released [v1.1.0](https://github.com/marketplace/actions/setup-minikube-kubernetes-cluster?version=v1.1.0) with support for your requests. Please confirm if this fulfills your needs.
I'd be very happy if you keep using this action in your workflows (makes me feel useful 😉), just reach out if you need anything else.
